# PLCTool project file

# External variables handling
isEmpty(PREFIX) {
  PREFIX=/usr/local
}

# Main binary target configuration
TARGET = PLCTool
QT += core gui widgets
TEMPLATE = app

SOURCES += \
    PLCTool/App/Application.cpp \
    PLCTool/App/DLMSProcessor.cpp \
    PLCTool/App/GXDLMSTranslatorInterface.cpp \
    PLCTool/App/MeterInfo.cpp \
    PLCTool/App/PRIMEProcessor.cpp \
    PLCTool/Attacks/Attack.cpp \
    PLCTool/Attacks/AttackController.cpp \
    PLCTool/Attacks/AttackFactory.cpp \
    PLCTool/Attacks/AttackFactoryLibrary.cpp \
    PLCTool/Attacks/AttackManager.cpp \
    PLCTool/Attacks/AttackManagerWorker.cpp \
    PLCTool/Attacks/AttackPluginLoader.cpp \
    PLCTool/Attacks/GenericUIAttackController.cpp \
    PLCTool/Attacks/UIAttackController.cpp \
    PLCTool/PRIME/PrimeAdapter.cpp \
    PLCTool/PRIME/PrimeFrame.cpp \
    PLCTool/PRIME/libprime/layer.c \
    PLCTool/PRIME/libprime/state.c \
    PLCTool/PRIME/spip/crc32.c \
    PLCTool/PRIME/spip/loop.c \
    PLCTool/PRIME/spip/serial.c \
    PLCTool/PRIME/spip/spip.c \
    PLCTool/Topology/Adapter.cpp \
    PLCTool/Topology/AdapterEventListener.cpp \
    PLCTool/Topology/Concentrator.cpp \
    PLCTool/Topology/Exception.cpp \
    PLCTool/Topology/Hub.cpp \
    PLCTool/Topology/Meter.cpp \
    PLCTool/Topology/Node.cpp \
    PLCTool/Topology/StringParams.cpp \
    PLCTool/Topology/SubNet.cpp \
    PLCTool/Topology/Switch.cpp \
    PLCTool/Topology/Worker.cpp \
    PLCTool/Types/ber/BerBitString.cpp \
    PLCTool/Types/ber/BerBoolean.cpp \
    PLCTool/Types/ber/BerContents.cpp \
    PLCTool/Types/ber/BerData.cpp \
    PLCTool/Types/ber/BerGraphicString.cpp \
    PLCTool/Types/ber/BerIdentifier.cpp \
    PLCTool/Types/ber/BerInteger.cpp \
    PLCTool/Types/ber/BerLength.cpp \
    PLCTool/Types/ber/BerObjectIdentifier.cpp \
    PLCTool/Types/ber/BerOctetString.cpp \
    PLCTool/Types/ber/BerPrimitiveBitString.cpp \
    PLCTool/Types/ber/BerPrimitiveGraphicString.cpp \
    PLCTool/Types/ber/BerPrimitiveOctetString.cpp \
    PLCTool/Types/ber/BitString.cpp \
    PLCTool/Types/ber/Integer.cpp \
    PLCTool/Types/ber/MarkedLongFormatInteger.cpp \
    PLCTool/Types/ber/MarklessLongFormatInteger.cpp \
    PLCTool/Types/ber/ObjectIdentifier.cpp \
    PLCTool/Types/ber/ber.c \
    PLCTool/Types/ber/parser.c \
    PLCTool/Types/ber/stream.c \
    PLCTool/Types/dlms/AarqApdu.cpp \
    PLCTool/Types/dlms/AcseRequirements.cpp \
    PLCTool/Types/dlms/ActionRequest.cpp \
    PLCTool/Types/dlms/ActionRequestNormal.cpp \
    PLCTool/Types/dlms/ApplicationContextName.cpp \
    PLCTool/Types/dlms/AssociationInformation.cpp \
    PLCTool/Types/dlms/AuthenticationValue.cpp \
    PLCTool/Types/dlms/Conformance.cpp \
    PLCTool/Types/dlms/CosemMethodDescriptor.cpp \
    PLCTool/Types/dlms/DataArray.cpp \
    PLCTool/Types/dlms/DataInteger.cpp \
    PLCTool/Types/dlms/GraphicStringAuthenticationValue.cpp \
    PLCTool/Types/dlms/InitiateRequestApdu.cpp \
    PLCTool/Types/dlms/InvokeIdAndPriority.cpp \
    PLCTool/Types/dlms/MechanismName.cpp \
    PLCTool/Types/dlms/ReleaseRequestReason.cpp \
    PLCTool/Types/dlms/RlrqApdu.cpp \
    PLCTool/Types/dlms/dlms.c \
    PLCTool/Types/dlms/dlmsmsg.c \
    PLCTool/Types/dlms/meter.c \
    PLCTool/Types/general/Bytevector.cpp \
    PLCTool/Ui/AttackUI.cpp \
    PLCTool/Ui/CredInfoTableModel.cpp \
    PLCTool/Ui/CredentialsUI.cpp \
    PLCTool/Ui/DLMSLogUI.cpp \
    PLCTool/Ui/DLMSTableModel.cpp \
    PLCTool/Ui/DisclaimerDialog.cpp \
    PLCTool/Ui/FrameLogUI.cpp \
    PLCTool/Ui/FrameTableModel.cpp \
    PLCTool/Ui/LoadingStatusDialog.cpp \
    PLCTool/Ui/MainWindow.cpp \
    PLCTool/Ui/MeterUI.cpp \
    PLCTool/Ui/ModemDialog.cpp \
    PLCTool/Ui/QtUi.cpp \
    PLCTool/Ui/TopologyModel.cpp \
    PLCTool/Ui/TranslatorUI.cpp \
    PLCTool/Ui/XMLHighlighter.cpp \
    PLCTool/gurux/src/GXAPDU.cpp \
    PLCTool/gurux/src/GXAdjacentCell.cpp \
    PLCTool/gurux/src/GXApplicationContextName.cpp \
    PLCTool/gurux/src/GXAuthenticationMechanismName.cpp \
    PLCTool/gurux/src/GXBitString.cpp \
    PLCTool/gurux/src/GXBytebuffer.cpp \
    PLCTool/gurux/src/GXChargePerUnitScaling.cpp \
    PLCTool/gurux/src/GXChargeTable.cpp \
    PLCTool/gurux/src/GXCipher.cpp \
    PLCTool/gurux/src/GXCommodity.cpp \
    PLCTool/gurux/src/GXCreditChargeConfiguration.cpp \
    PLCTool/gurux/src/GXCurrency.cpp \
    PLCTool/gurux/src/GXDLMS.cpp \
    PLCTool/gurux/src/GXDLMSAccount.cpp \
    PLCTool/gurux/src/GXDLMSActionItem.cpp \
    PLCTool/gurux/src/GXDLMSActionSchedule.cpp \
    PLCTool/gurux/src/GXDLMSActionSet.cpp \
    PLCTool/gurux/src/GXDLMSActivityCalendar.cpp \
    PLCTool/gurux/src/GXDLMSAssociationLogicalName.cpp \
    PLCTool/gurux/src/GXDLMSAssociationShortName.cpp \
    PLCTool/gurux/src/GXDLMSAutoAnswer.cpp \
    PLCTool/gurux/src/GXDLMSAutoConnect.cpp \
    PLCTool/gurux/src/GXDLMSCaptureObject.cpp \
    PLCTool/gurux/src/GXDLMSCertificateInfo.cpp \
    PLCTool/gurux/src/GXDLMSCharge.cpp \
    PLCTool/gurux/src/GXDLMSClient.cpp \
    PLCTool/gurux/src/GXDLMSClock.cpp \
    PLCTool/gurux/src/GXDLMSCompactData.cpp \
    PLCTool/gurux/src/GXDLMSContextType.cpp \
    PLCTool/gurux/src/GXDLMSConverter.cpp \
    PLCTool/gurux/src/GXDLMSCredit.cpp \
    PLCTool/gurux/src/GXDLMSData.cpp \
    PLCTool/gurux/src/GXDLMSDayProfile.cpp \
    PLCTool/gurux/src/GXDLMSDayProfileAction.cpp \
    PLCTool/gurux/src/GXDLMSDemandRegister.cpp \
    PLCTool/gurux/src/GXDLMSDisconnectControl.cpp \
    PLCTool/gurux/src/GXDLMSEmergencyProfile.cpp \
    PLCTool/gurux/src/GXDLMSExtendedRegister.cpp \
    PLCTool/gurux/src/GXDLMSGPRSSetup.cpp \
    PLCTool/gurux/src/GXDLMSGSMCellInfo.cpp \
    PLCTool/gurux/src/GXDLMSGSMDiagnostic.cpp \
    PLCTool/gurux/src/GXDLMSHdlcSetup.cpp \
    PLCTool/gurux/src/GXDLMSIECOpticalPortSetup.cpp \
    PLCTool/gurux/src/GXDLMSImageActivateInfo.cpp \
    PLCTool/gurux/src/GXDLMSImageTransfer.cpp \
    PLCTool/gurux/src/GXDLMSIp4Setup.cpp \
    PLCTool/gurux/src/GXDLMSIp4SetupIpOption.cpp \
    PLCTool/gurux/src/GXDLMSLNCommandHandler.cpp \
    PLCTool/gurux/src/GXDLMSLNParameters.cpp \
    PLCTool/gurux/src/GXDLMSLimiter.cpp \
    PLCTool/gurux/src/GXDLMSLimits.cpp \
    PLCTool/gurux/src/GXDLMSLlcSscsSetup.cpp \
    PLCTool/gurux/src/GXDLMSMBusClient.cpp \
    PLCTool/gurux/src/GXDLMSMBusMasterPortSetup.cpp \
    PLCTool/gurux/src/GXDLMSMBusSlavePortSetup.cpp \
    PLCTool/gurux/src/GXDLMSMacAddressSetup.cpp \
    PLCTool/gurux/src/GXDLMSMd5.cpp \
    PLCTool/gurux/src/GXDLMSMessageHandler.cpp \
    PLCTool/gurux/src/GXDLMSModemConfiguration.cpp \
    PLCTool/gurux/src/GXDLMSModemInitialisation.cpp \
    PLCTool/gurux/src/GXDLMSMonitoredValue.cpp \
    PLCTool/gurux/src/GXDLMSNotify.cpp \
    PLCTool/gurux/src/GXDLMSObject.cpp \
    PLCTool/gurux/src/GXDLMSObjectCollection.cpp \
    PLCTool/gurux/src/GXDLMSObjectDefinition.cpp \
    PLCTool/gurux/src/GXDLMSObjectFactory.cpp \
    PLCTool/gurux/src/GXDLMSParameterMonitor.cpp \
    PLCTool/gurux/src/GXDLMSPppSetup.cpp \
    PLCTool/gurux/src/GXDLMSPppSetupIPCPOption.cpp \
    PLCTool/gurux/src/GXDLMSPppSetupLcpOption.cpp \
    PLCTool/gurux/src/GXDLMSPrimeNbOfdmPlcApplicationsIdentification.cpp \
    PLCTool/gurux/src/GXDLMSPrimeNbOfdmPlcMacCounters.cpp \
    PLCTool/gurux/src/GXDLMSPrimeNbOfdmPlcMacFunctionalParameters.cpp \
    PLCTool/gurux/src/GXDLMSPrimeNbOfdmPlcMacNetworkAdministrationData.cpp \
    PLCTool/gurux/src/GXDLMSPrimeNbOfdmPlcMacSetup.cpp \
    PLCTool/gurux/src/GXDLMSPrimeNbOfdmPlcPhysicalLayerCounters.cpp \
    PLCTool/gurux/src/GXDLMSProfileGeneric.cpp \
    PLCTool/gurux/src/GXDLMSPushObject.cpp \
    PLCTool/gurux/src/GXDLMSPushSetup.cpp \
    PLCTool/gurux/src/GXDLMSQualityOfService.cpp \
    PLCTool/gurux/src/GXDLMSRegister.cpp \
    PLCTool/gurux/src/GXDLMSRegisterActivation.cpp \
    PLCTool/gurux/src/GXDLMSRegisterMonitor.cpp \
    PLCTool/gurux/src/GXDLMSSNCommandHandler.cpp \
    PLCTool/gurux/src/GXDLMSSNParameters.cpp \
    PLCTool/gurux/src/GXDLMSSapAssignment.cpp \
    PLCTool/gurux/src/GXDLMSSchedule.cpp \
    PLCTool/gurux/src/GXDLMSScheduleEntry.cpp \
    PLCTool/gurux/src/GXDLMSScript.cpp \
    PLCTool/gurux/src/GXDLMSScriptAction.cpp \
    PLCTool/gurux/src/GXDLMSScriptTable.cpp \
    PLCTool/gurux/src/GXDLMSSeasonProfile.cpp \
    PLCTool/gurux/src/GXDLMSSecureClient.cpp \
    PLCTool/gurux/src/GXDLMSSecureServer.cpp \
    PLCTool/gurux/src/GXDLMSSecuritySetup.cpp \
    PLCTool/gurux/src/GXDLMSServer.cpp \
    PLCTool/gurux/src/GXDLMSSettings.cpp \
    PLCTool/gurux/src/GXDLMSSha1.cpp \
    PLCTool/gurux/src/GXDLMSSha256.cpp \
    PLCTool/gurux/src/GXDLMSSpecialDay.cpp \
    PLCTool/gurux/src/GXDLMSSpecialDaysTable.cpp \
    PLCTool/gurux/src/GXDLMSTarget.cpp \
    PLCTool/gurux/src/GXDLMSTcpUdpSetup.cpp \
    PLCTool/gurux/src/GXDLMSTokenGateway.cpp \
    PLCTool/gurux/src/GXDLMSTranslator.cpp \
    PLCTool/gurux/src/GXDLMSTranslatorStructure.cpp \
    PLCTool/gurux/src/GXDLMSUtilityTables.cpp \
    PLCTool/gurux/src/GXDLMSValueEventArg.cpp \
    PLCTool/gurux/src/GXDLMSVariant.cpp \
    PLCTool/gurux/src/GXDLMSWeekProfile.cpp \
    PLCTool/gurux/src/GXDateTime.cpp \
    PLCTool/gurux/src/GXHelpers.cpp \
    PLCTool/gurux/src/GXReplyData.cpp \
    PLCTool/gurux/src/GXSNInfo.cpp \
    PLCTool/gurux/src/GXSecure.cpp \
    PLCTool/gurux/src/GXSerialNumberCounter.cpp \
    PLCTool/gurux/src/GXStandardObisCode.cpp \
    PLCTool/gurux/src/GXStandardObisCodeCollection.cpp \
    PLCTool/gurux/src/GXTokenGatewayConfiguration.cpp \
    PLCTool/gurux/src/GXUnitCharge.cpp \
    PLCTool/gurux/src/GXXmlReader.cpp \
    PLCTool/gurux/src/GXXmlWriter.cpp \
    PLCTool/gurux/src/GXXmlWriterSettings.cpp \
    PLCTool/main.cpp \
    PLCTool/util/util.c

HEADERS += \
    PLCTool/App/Application.h \
    PLCTool/App/DLMSProcessor.h \
    PLCTool/App/DLMSTranslator.h \
    PLCTool/App/GXDLMSTranslatorInterface.h \
    PLCTool/App/MeterInfo.h \
    PLCTool/App/PRIMEProcessor.h \
    PLCTool/Attacks/Attack.h \
    PLCTool/Attacks/AttackController.h \
    PLCTool/Attacks/AttackFactory.h \
    PLCTool/Attacks/AttackFactoryLibrary.h \
    PLCTool/Attacks/AttackManager.h \
    PLCTool/Attacks/AttackManagerWorker.h \
    PLCTool/Attacks/AttackPluginLoader.h \
    PLCTool/Attacks/GenericUIAttackController.h \
    PLCTool/Attacks/UIAttackController.h \
    PLCTool/PRIME/PrimeAdapter.h \
    PLCTool/PRIME/PrimeFrame.h \
    PLCTool/PRIME/libprime/layer.h \
    PLCTool/PRIME/libprime/pdu.h \
    PLCTool/PRIME/libprime/prime.h \
    PLCTool/PRIME/libprime/state.h \
    PLCTool/PRIME/spip/spip.h \
    PLCTool/Topology/Adapter.h \
    PLCTool/Topology/AdapterEventListener.h \
    PLCTool/Topology/Concentrator.h \
    PLCTool/Topology/Exception.h \
    PLCTool/Topology/Hub.h \
    PLCTool/Topology/Meter.h \
    PLCTool/Topology/Node.h \
    PLCTool/Topology/StringParams.h \
    PLCTool/Topology/SubNet.h \
    PLCTool/Topology/Switch.h \
    PLCTool/Topology/Worker.h \
    PLCTool/Types/ber/BerBitString.h \
    PLCTool/Types/ber/BerBoolean.h \
    PLCTool/Types/ber/BerContents.h \
    PLCTool/Types/ber/BerData.h \
    PLCTool/Types/ber/BerGraphicString.h \
    PLCTool/Types/ber/BerIdentifier.h \
    PLCTool/Types/ber/BerInteger.h \
    PLCTool/Types/ber/BerLength.h \
    PLCTool/Types/ber/BerObjectIdentifier.h \
    PLCTool/Types/ber/BerOctetString.h \
    PLCTool/Types/ber/BerPrimitiveBitString.h \
    PLCTool/Types/ber/BerPrimitiveGraphicString.h \
    PLCTool/Types/ber/BerPrimitiveOctetString.h \
    PLCTool/Types/ber/BitString.h \
    PLCTool/Types/ber/Integer.h \
    PLCTool/Types/ber/LongFormatInteger.h \
    PLCTool/Types/ber/MarkedLongFormatInteger.h \
    PLCTool/Types/ber/MarklessLongFormatInteger.h \
    PLCTool/Types/ber/ObjectIdentifier.h \
    PLCTool/Types/ber/ber.h \
    PLCTool/Types/ber/stream.h \
    PLCTool/Types/dlms/AarqApdu.h \
    PLCTool/Types/dlms/AcseApdu.h \
    PLCTool/Types/dlms/AcseRequirements.h \
    PLCTool/Types/dlms/ActionRequest.h \
    PLCTool/Types/dlms/ActionRequestNormal.h \
    PLCTool/Types/dlms/ApplicationContextName.h \
    PLCTool/Types/dlms/AssociationInformation.h \
    PLCTool/Types/dlms/AuthenticationValue.h \
    PLCTool/Types/dlms/Conformance.h \
    PLCTool/Types/dlms/CosemMethodDescriptor.h \
    PLCTool/Types/dlms/Data.h \
    PLCTool/Types/dlms/DataArray.h \
    PLCTool/Types/dlms/DataInteger.h \
    PLCTool/Types/dlms/DlmsMessageType.h \
    PLCTool/Types/dlms/GraphicStringAuthenticationValue.h \
    PLCTool/Types/dlms/InitiateRequestApdu.h \
    PLCTool/Types/dlms/InvokeIdAndPriority.h \
    PLCTool/Types/dlms/MechanismName.h \
    PLCTool/Types/dlms/ReleaseRequestReason.h \
    PLCTool/Types/dlms/RlrqApdu.h \
    PLCTool/Types/dlms/XDlmsApdu.h \
    PLCTool/Types/dlms/dlms.h \
    PLCTool/Types/dlms/dlmsmsg.h \
    PLCTool/Types/dlms/meter.h \
    PLCTool/Types/general/Bytevector.h \
    PLCTool/Types/general/Serializable.h \
    PLCTool/Ui/AttackUI.h \
    PLCTool/Ui/CredInfoTableModel.h \
    PLCTool/Ui/CredentialsUI.h \
    PLCTool/Ui/DLMSLogUI.h \
    PLCTool/Ui/DLMSTableModel.h \
    PLCTool/Ui/DisclaimerDialog.h \
    PLCTool/Ui/FrameLogUI.h \
    PLCTool/Ui/FrameTableModel.h \
    PLCTool/Ui/LoadingStatusDialog.h \
    PLCTool/Ui/MainWindow.h \
    PLCTool/Ui/MeterUI.h \
    PLCTool/Ui/ModemDialog.h \
    PLCTool/Ui/QtUi.h \
    PLCTool/Ui/TopologyModel.h \
    PLCTool/Ui/TranslatorUI.h \
    PLCTool/Ui/XMLHighlighter.h \
    PLCTool/gurux/include/GXAPDU.h \
    PLCTool/gurux/include/GXAdjacentCell.h \
    PLCTool/gurux/include/GXApplicationContextName.h \
    PLCTool/gurux/include/GXAttributeCollection.h \
    PLCTool/gurux/include/GXAuthentication.h \
    PLCTool/gurux/include/GXAuthenticationMechanismName.h \
    PLCTool/gurux/include/GXBitString.h \
    PLCTool/gurux/include/GXBytebuffer.h \
    PLCTool/gurux/include/GXChargePerUnitScaling.h \
    PLCTool/gurux/include/GXChargeTable.h \
    PLCTool/gurux/include/GXCipher.h \
    PLCTool/gurux/include/GXCommodity.h \
    PLCTool/gurux/include/GXCreditChargeConfiguration.h \
    PLCTool/gurux/include/GXCurrency.h \
    PLCTool/gurux/include/GXDLMS.h \
    PLCTool/gurux/include/GXDLMSAccount.h \
    PLCTool/gurux/include/GXDLMSActionItem.h \
    PLCTool/gurux/include/GXDLMSActionSchedule.h \
    PLCTool/gurux/include/GXDLMSActionSet.h \
    PLCTool/gurux/include/GXDLMSActivityCalendar.h \
    PLCTool/gurux/include/GXDLMSAssociationLogicalName.h \
    PLCTool/gurux/include/GXDLMSAssociationShortName.h \
    PLCTool/gurux/include/GXDLMSAttribute.h \
    PLCTool/gurux/include/GXDLMSAutoAnswer.h \
    PLCTool/gurux/include/GXDLMSAutoConnect.h \
    PLCTool/gurux/include/GXDLMSCaptureObject.h \
    PLCTool/gurux/include/GXDLMSCertificateInfo.h \
    PLCTool/gurux/include/GXDLMSCharge.h \
    PLCTool/gurux/include/GXDLMSClient.h \
    PLCTool/gurux/include/GXDLMSClock.h \
    PLCTool/gurux/include/GXDLMSCompactData.h \
    PLCTool/gurux/include/GXDLMSConnectionEventArgs.h \
    PLCTool/gurux/include/GXDLMSContextType.h \
    PLCTool/gurux/include/GXDLMSConverter.h \
    PLCTool/gurux/include/GXDLMSCredit.h \
    PLCTool/gurux/include/GXDLMSData.h \
    PLCTool/gurux/include/GXDLMSDayProfile.h \
    PLCTool/gurux/include/GXDLMSDayProfileAction.h \
    PLCTool/gurux/include/GXDLMSDemandRegister.h \
    PLCTool/gurux/include/GXDLMSDisconnectControl.h \
    PLCTool/gurux/include/GXDLMSEmergencyProfile.h \
    PLCTool/gurux/include/GXDLMSExtendedRegister.h \
    PLCTool/gurux/include/GXDLMSGPRSSetup.h \
    PLCTool/gurux/include/GXDLMSGSMCellInfo.h \
    PLCTool/gurux/include/GXDLMSGSMDiagnostic.h \
    PLCTool/gurux/include/GXDLMSHdlcSetup.h \
    PLCTool/gurux/include/GXDLMSIECOpticalPortSetup.h \
    PLCTool/gurux/include/GXDLMSImageActivateInfo.h \
    PLCTool/gurux/include/GXDLMSImageTransfer.h \
    PLCTool/gurux/include/GXDLMSIp4Setup.h \
    PLCTool/gurux/include/GXDLMSIp4SetupIpOption.h \
    PLCTool/gurux/include/GXDLMSLNCommandHandler.h \
    PLCTool/gurux/include/GXDLMSLNParameters.h \
    PLCTool/gurux/include/GXDLMSLimiter.h \
    PLCTool/gurux/include/GXDLMSLimits.h \
    PLCTool/gurux/include/GXDLMSLlcSscsSetup.h \
    PLCTool/gurux/include/GXDLMSLongTransaction.h \
    PLCTool/gurux/include/GXDLMSMBusClient.h \
    PLCTool/gurux/include/GXDLMSMBusMasterPortSetup.h \
    PLCTool/gurux/include/GXDLMSMBusSlavePortSetup.h \
    PLCTool/gurux/include/GXDLMSMacAddressSetup.h \
    PLCTool/gurux/include/GXDLMSMd5.h \
    PLCTool/gurux/include/GXDLMSMessageHandler.h \
    PLCTool/gurux/include/GXDLMSModemConfiguration.h \
    PLCTool/gurux/include/GXDLMSModemInitialisation.h \
    PLCTool/gurux/include/GXDLMSMonitoredValue.h \
    PLCTool/gurux/include/GXDLMSNotify.h \
    PLCTool/gurux/include/GXDLMSObject.h \
    PLCTool/gurux/include/GXDLMSObjectCollection.h \
    PLCTool/gurux/include/GXDLMSObjectDefinition.h \
    PLCTool/gurux/include/GXDLMSObjectFactory.h \
    PLCTool/gurux/include/GXDLMSParameterMonitor.h \
    PLCTool/gurux/include/GXDLMSPppSetup.h \
    PLCTool/gurux/include/GXDLMSPppSetupIPCPOption.h \
    PLCTool/gurux/include/GXDLMSPppSetupLcpOption.h \
    PLCTool/gurux/include/GXDLMSPrimeNbOfdmPlcApplicationsIdentification.h \
    PLCTool/gurux/include/GXDLMSPrimeNbOfdmPlcMacCounters.h \
    PLCTool/gurux/include/GXDLMSPrimeNbOfdmPlcMacFunctionalParameters.h \
    PLCTool/gurux/include/GXDLMSPrimeNbOfdmPlcMacNetworkAdministrationData.h \
    PLCTool/gurux/include/GXDLMSPrimeNbOfdmPlcMacSetup.h \
    PLCTool/gurux/include/GXDLMSPrimeNbOfdmPlcPhysicalLayerCounters.h \
    PLCTool/gurux/include/GXDLMSProfileGeneric.h \
    PLCTool/gurux/include/GXDLMSPushObject.h \
    PLCTool/gurux/include/GXDLMSPushSetup.h \
    PLCTool/gurux/include/GXDLMSQualityOfService.h \
    PLCTool/gurux/include/GXDLMSRegister.h \
    PLCTool/gurux/include/GXDLMSRegisterActivation.h \
    PLCTool/gurux/include/GXDLMSRegisterMonitor.h \
    PLCTool/gurux/include/GXDLMSSNCommandHandler.h \
    PLCTool/gurux/include/GXDLMSSNParameters.h \
    PLCTool/gurux/include/GXDLMSSapAssignment.h \
    PLCTool/gurux/include/GXDLMSSchedule.h \
    PLCTool/gurux/include/GXDLMSScheduleEntry.h \
    PLCTool/gurux/include/GXDLMSScript.h \
    PLCTool/gurux/include/GXDLMSScriptAction.h \
    PLCTool/gurux/include/GXDLMSScriptTable.h \
    PLCTool/gurux/include/GXDLMSSeasonProfile.h \
    PLCTool/gurux/include/GXDLMSSecureClient.h \
    PLCTool/gurux/include/GXDLMSSecureServer.h \
    PLCTool/gurux/include/GXDLMSSecuritySetup.h \
    PLCTool/gurux/include/GXDLMSServer.h \
    PLCTool/gurux/include/GXDLMSSettings.h \
    PLCTool/gurux/include/GXDLMSSha1.h \
    PLCTool/gurux/include/GXDLMSSha256.h \
    PLCTool/gurux/include/GXDLMSSpecialDay.h \
    PLCTool/gurux/include/GXDLMSSpecialDaysTable.h \
    PLCTool/gurux/include/GXDLMSTarget.h \
    PLCTool/gurux/include/GXDLMSTcpUdpSetup.h \
    PLCTool/gurux/include/GXDLMSTokenGateway.h \
    PLCTool/gurux/include/GXDLMSTranslator.h \
    PLCTool/gurux/include/GXDLMSTranslatorStructure.h \
    PLCTool/gurux/include/GXDLMSUtilityTables.h \
    PLCTool/gurux/include/GXDLMSValueEventArg.h \
    PLCTool/gurux/include/GXDLMSValueEventCollection.h \
    PLCTool/gurux/include/GXDLMSVariant.h \
    PLCTool/gurux/include/GXDLMSWeekProfile.h \
    PLCTool/gurux/include/GXDataInfo.h \
    PLCTool/gurux/include/GXDate.h \
    PLCTool/gurux/include/GXDateTime.h \
    PLCTool/gurux/include/GXHelpers.h \
    PLCTool/gurux/include/GXMacAvailableSwitch.h \
    PLCTool/gurux/include/GXMacDirectTable.h \
    PLCTool/gurux/include/GXMacMulticastEntry.h \
    PLCTool/gurux/include/GXMacPhyCommunication.h \
    PLCTool/gurux/include/GXReplyData.h \
    PLCTool/gurux/include/GXSNInfo.h \
    PLCTool/gurux/include/GXSecure.h \
    PLCTool/gurux/include/GXSerialNumberCounter.h \
    PLCTool/gurux/include/GXServerReply.h \
    PLCTool/gurux/include/GXStandardObisCode.h \
    PLCTool/gurux/include/GXStandardObisCodeCollection.h \
    PLCTool/gurux/include/GXTime.h \
    PLCTool/gurux/include/GXTokenGatewayConfiguration.h \
    PLCTool/gurux/include/GXUnitCharge.h \
    PLCTool/gurux/include/GXXmlReader.h \
    PLCTool/gurux/include/GXXmlWriter.h \
    PLCTool/gurux/include/GXXmlWriterSettings.h \
    PLCTool/gurux/include/IGXDLMSBase.h \
    PLCTool/gurux/include/OBiscodes.h \
    PLCTool/gurux/include/TranslatorGeneralTags.h \
    PLCTool/gurux/include/TranslatorSimpleTags.h \
    PLCTool/gurux/include/TranslatorStandardTags.h \
    PLCTool/gurux/include/TranslatorTags.h \
    PLCTool/gurux/include/chipperingenums.h \
    PLCTool/gurux/include/enums.h \
    PLCTool/gurux/include/errorcodes.h \
    PLCTool/util/defs.h \
    PLCTool/util/util.h

FORMS += \
    PLCTool/Forms/AttackUI.ui \
    PLCTool/Forms/CredentialsUI.ui \
    PLCTool/Forms/DLMSLogUI.ui \
    PLCTool/Forms/DisclaimerDialog.ui \
    PLCTool/Forms/FrameLogUI.ui \
    PLCTool/Forms/LoadingStatusDialog.ui \
    PLCTool/Forms/MainWindow.ui \
    PLCTool/Forms/MeterUI.ui \
    PLCTool/Forms/ModemDialog.ui \
    PLCTool/Forms/TranslatorUI.ui

RESOURCES += \
    PLCTool/icons.qrc

QMAKE_LFLAGS += -rdynamic

unix: LIBS += -ldl

target.path=$$PREFIX/bin

INSTALLS += target


# API headers target configuration
INSTALL_HEADERS_PREFIX = $$PREFIX/include/

INSTALL_HEADERS  += \
    PLCTool/App/DLMSTranslrtor.h \
    PLCTool/App/GXDLMSTranslatorInterface.h \
    PLCTool/Attacks/Attack.h \
    PLCTool/Attacks/AttackFactory.h \
    PLCTool/Attacks/AttackFactoryLibrary.h \
    PLCTool/Topology/Adapter.h \
    PLCTool/Topology/AdapterEventListener.h \
    PLCTool/Topology/Concentrator.h \
    PLCTool/Topology/Exception.h \
    PLCTool/Topology/Hub.h \
    PLCTool/Topology/Meter.h \
    PLCTool/Topology/Node.h \
    PLCTool/Topology/StringParams.h \
    PLCTool/Topology/SubNet.h \
    PLCTool/Topology/Switch.h \
    PLCTool/Topology/Worker.h \
    PLCTool/PRIME/libprime/layer.h \
    PLCTool/PRIME/libprime/pdu.h \
    PLCTool/PRIME/libprime/prime.h \
    PLCTool/PRIME/libprime/state.h \
    PLCTool/PRIME/PrimeFrame.h \
    PLCTool/PRIME/PrimeAdapter.h \
    PLCTool/Types/ber/BerBitString.h \
    PLCTool/Types/ber/BerBoolean.h \
    PLCTool/Types/ber/BerContents.h \
    PLCTool/Types/ber/BerData.h \
    PLCTool/Types/ber/BerGraphicString.h \
    PLCTool/Types/ber/BerIdentifier.h \
    PLCTool/Types/ber/BerInteger.h \
    PLCTool/Types/ber/BerLength.h \
    PLCTool/Types/ber/BerObjectIdentifier.h \
    PLCTool/Types/ber/BerOctetString.h \
    PLCTool/Types/ber/BerPrimitiveBitString.h \
    PLCTool/Types/ber/BerPrimitiveGraphicString.h \
    PLCTool/Types/ber/BerPrimitiveOctetString.h \
    PLCTool/Types/ber/BitString.h \
    PLCTool/Types/general/Bytevector.h \
    PLCTool/Types/ber/Integer.h \
    PLCTool/Types/ber/LongFormatInteger.h \
    PLCTool/Types/ber/MarkedLongFormatInteger.h \
    PLCTool/Types/ber/MarklessLongFormatInteger.h \
    PLCTool/Types/ber/ObjectIdentifier.h \
    PLCTool/Types/general/Serializable.h \
    PLCTool/Types/ber/ber.h \
    PLCTool/Types/ber/stream.h \
    PLCTool/Types/dlms/AarqApdu.h \
    PLCTool/Types/dlms/AcseApdu.h \
    PLCTool/Types/dlms/AcseRequirements.h \
    PLCTool/Types/dlms/ActionRequest.h \
    PLCTool/Types/dlms/ActionRequestNormal.h \
    PLCTool/Types/dlms/ApplicationContextName.h \
    PLCTool/Types/dlms/AssociationInformation.h \
    PLCTool/Types/dlms/AuthenticationValue.h \
    PLCTool/Types/dlms/Conformance.h \
    PLCTool/Types/dlms/CosemMethodDescriptor.h \
    PLCTool/Types/dlms/Data.h \
    PLCTool/Types/dlms/DataArray.h \
    PLCTool/Types/dlms/DataInteger.h \
    PLCTool/Types/dlms/DlmsMessageType.h \
    PLCTool/Types/dlms/GraphicStringAuthenticationValue.h \
    PLCTool/Types/dlms/InitiateRequestApdu.h \
    PLCTool/Types/dlms/InvokeIdAndPriority.h \
    PLCTool/Types/dlms/MechanismName.h \
    PLCTool/Types/dlms/ReleaseRequestReason.h \
    PLCTool/Types/dlms/RlrqApdu.h \
    PLCTool/Types/dlms/XDlmsApdu.h \
    PLCTool/Types/dlms/dlms.h \
    PLCTool/Types/dlms/dlmsmsg.h \
    PLCTool/Types/dlms/meter.h \
    PLCTool/gurux/include/GXAPDU.h \
    PLCTool/gurux/include/GXAdjacentCell.h \
    PLCTool/gurux/include/GXApplicationContextName.h \
    PLCTool/gurux/include/GXAttributeCollection.h \
    PLCTool/gurux/include/GXAuthentication.h \
    PLCTool/gurux/include/GXAuthenticationMechanismName.h \
    PLCTool/gurux/include/GXBitString.h \
    PLCTool/gurux/include/GXBytebuffer.h \
    PLCTool/gurux/include/GXChargePerUnitScaling.h \
    PLCTool/gurux/include/GXChargeTable.h \
    PLCTool/gurux/include/GXCipher.h \
    PLCTool/gurux/include/GXCommodity.h \
    PLCTool/gurux/include/GXCreditChargeConfiguration.h \
    PLCTool/gurux/include/GXCurrency.h \
    PLCTool/gurux/include/GXDLMS.h \
    PLCTool/gurux/include/GXDLMSAccount.h \
    PLCTool/gurux/include/GXDLMSActionItem.h \
    PLCTool/gurux/include/GXDLMSActionSchedule.h \
    PLCTool/gurux/include/GXDLMSActionSet.h \
    PLCTool/gurux/include/GXDLMSActivityCalendar.h \
    PLCTool/gurux/include/GXDLMSAssociationLogicalName.h \
    PLCTool/gurux/include/GXDLMSAssociationShortName.h \
    PLCTool/gurux/include/GXDLMSAttribute.h \
    PLCTool/gurux/include/GXDLMSAutoAnswer.h \
    PLCTool/gurux/include/GXDLMSAutoConnect.h \
    PLCTool/gurux/include/GXDLMSCaptureObject.h \
    PLCTool/gurux/include/GXDLMSCertificateInfo.h \
    PLCTool/gurux/include/GXDLMSCharge.h \
    PLCTool/gurux/include/GXDLMSClient.h \
    PLCTool/gurux/include/GXDLMSClock.h \
    PLCTool/gurux/include/GXDLMSCompactData.h \
    PLCTool/gurux/include/GXDLMSConnectionEventArgs.h \
    PLCTool/gurux/include/GXDLMSContextType.h \
    PLCTool/gurux/include/GXDLMSConverter.h \
    PLCTool/gurux/include/GXDLMSCredit.h \
    PLCTool/gurux/include/GXDLMSData.h \
    PLCTool/gurux/include/GXDLMSDayProfile.h \
    PLCTool/gurux/include/GXDLMSDayProfileAction.h \
    PLCTool/gurux/include/GXDLMSDemandRegister.h \
    PLCTool/gurux/include/GXDLMSDisconnectControl.h \
    PLCTool/gurux/include/GXDLMSEmergencyProfile.h \
    PLCTool/gurux/include/GXDLMSExtendedRegister.h \
    PLCTool/gurux/include/GXDLMSGPRSSetup.h \
    PLCTool/gurux/include/GXDLMSGSMCellInfo.h \
    PLCTool/gurux/include/GXDLMSGSMDiagnostic.h \
    PLCTool/gurux/include/GXDLMSHdlcSetup.h \
    PLCTool/gurux/include/GXDLMSIECOpticalPortSetup.h \
    PLCTool/gurux/include/GXDLMSImageActivateInfo.h \
    PLCTool/gurux/include/GXDLMSImageTransfer.h \
    PLCTool/gurux/include/GXDLMSIp4Setup.h \
    PLCTool/gurux/include/GXDLMSIp4SetupIpOption.h \
    PLCTool/gurux/include/GXDLMSLNCommandHandler.h \
    PLCTool/gurux/include/GXDLMSLNParameters.h \
    PLCTool/gurux/include/GXDLMSLimiter.h \
    PLCTool/gurux/include/GXDLMSLimits.h \
    PLCTool/gurux/include/GXDLMSLlcSscsSetup.h \
    PLCTool/gurux/include/GXDLMSLongTransaction.h \
    PLCTool/gurux/include/GXDLMSMBusClient.h \
    PLCTool/gurux/include/GXDLMSMBusMasterPortSetup.h \
    PLCTool/gurux/include/GXDLMSMBusSlavePortSetup.h \
    PLCTool/gurux/include/GXDLMSMacAddressSetup.h \
    PLCTool/gurux/include/GXDLMSMd5.h \
    PLCTool/gurux/include/GXDLMSMessageHandler.h \
    PLCTool/gurux/include/GXDLMSModemConfiguration.h \
    PLCTool/gurux/include/GXDLMSModemInitialisation.h \
    PLCTool/gurux/include/GXDLMSMonitoredValue.h \
    PLCTool/gurux/include/GXDLMSNotify.h \
    PLCTool/gurux/include/GXDLMSObject.h \
    PLCTool/gurux/include/GXDLMSObjectCollection.h \
    PLCTool/gurux/include/GXDLMSObjectDefinition.h \
    PLCTool/gurux/include/GXDLMSObjectFactory.h \
    PLCTool/gurux/include/GXDLMSParameterMonitor.h \
    PLCTool/gurux/include/GXDLMSPppSetup.h \
    PLCTool/gurux/include/GXDLMSPppSetupIPCPOption.h \
    PLCTool/gurux/include/GXDLMSPppSetupLcpOption.h \
    PLCTool/gurux/include/GXDLMSPrimeNbOfdmPlcApplicationsIdentification.h \
    PLCTool/gurux/include/GXDLMSPrimeNbOfdmPlcMacCounters.h \
    PLCTool/gurux/include/GXDLMSPrimeNbOfdmPlcMacFunctionalParameters.h \
    PLCTool/gurux/include/GXDLMSPrimeNbOfdmPlcMacNetworkAdministrationData.h \
    PLCTool/gurux/include/GXDLMSPrimeNbOfdmPlcMacSetup.h \
    PLCTool/gurux/include/GXDLMSPrimeNbOfdmPlcPhysicalLayerCounters.h \
    PLCTool/gurux/include/GXDLMSProfileGeneric.h \
    PLCTool/gurux/include/GXDLMSPushObject.h \
    PLCTool/gurux/include/GXDLMSPushSetup.h \
    PLCTool/gurux/include/GXDLMSQualityOfService.h \
    PLCTool/gurux/include/GXDLMSRegister.h \
    PLCTool/gurux/include/GXDLMSRegisterActivation.h \
    PLCTool/gurux/include/GXDLMSRegisterMonitor.h \
    PLCTool/gurux/include/GXDLMSSNCommandHandler.h \
    PLCTool/gurux/include/GXDLMSSNParameters.h \
    PLCTool/gurux/include/GXDLMSSapAssignment.h \
    PLCTool/gurux/include/GXDLMSSchedule.h \
    PLCTool/gurux/include/GXDLMSScheduleEntry.h \
    PLCTool/gurux/include/GXDLMSScript.h \
    PLCTool/gurux/include/GXDLMSScriptAction.h \
    PLCTool/gurux/include/GXDLMSScriptTable.h \
    PLCTool/gurux/include/GXDLMSSeasonProfile.h \
    PLCTool/gurux/include/GXDLMSSecureClient.h \
    PLCTool/gurux/include/GXDLMSSecureServer.h \
    PLCTool/gurux/include/GXDLMSSecuritySetup.h \
    PLCTool/gurux/include/GXDLMSServer.h \
    PLCTool/gurux/include/GXDLMSSettings.h \
    PLCTool/gurux/include/GXDLMSSha1.h \
    PLCTool/gurux/include/GXDLMSSha256.h \
    PLCTool/gurux/include/GXDLMSSpecialDay.h \
    PLCTool/gurux/include/GXDLMSSpecialDaysTable.h \
    PLCTool/gurux/include/GXDLMSTarget.h \
    PLCTool/gurux/include/GXDLMSTcpUdpSetup.h \
    PLCTool/gurux/include/GXDLMSTokenGateway.h \
    PLCTool/gurux/include/GXDLMSTranslator.h \
    PLCTool/gurux/include/GXDLMSTranslatorStructure.h \
    PLCTool/gurux/include/GXDLMSUtilityTables.h \
    PLCTool/gurux/include/GXDLMSValueEventArg.h \
    PLCTool/gurux/include/GXDLMSValueEventCollection.h \
    PLCTool/gurux/include/GXDLMSVariant.h \
    PLCTool/gurux/include/GXDLMSWeekProfile.h \
    PLCTool/gurux/include/GXDataInfo.h \
    PLCTool/gurux/include/GXDate.h \
    PLCTool/gurux/include/GXDateTime.h \
    PLCTool/gurux/include/GXHelpers.h \
    PLCTool/gurux/include/GXMacAvailableSwitch.h \
    PLCTool/gurux/include/GXMacDirectTable.h \
    PLCTool/gurux/include/GXMacMulticastEntry.h \
    PLCTool/gurux/include/GXMacPhyCommunication.h \
    PLCTool/gurux/include/GXReplyData.h \
    PLCTool/gurux/include/GXSNInfo.h \
    PLCTool/gurux/include/GXSecure.h \
    PLCTool/gurux/include/GXSerialNumberCounter.h \
    PLCTool/gurux/include/GXServerReply.h \
    PLCTool/gurux/include/GXStandardObisCode.h \
    PLCTool/gurux/include/GXStandardObisCodeCollection.h \
    PLCTool/gurux/include/GXTime.h \
    PLCTool/gurux/include/GXTokenGatewayConfiguration.h \
    PLCTool/gurux/include/GXUnitCharge.h \
    PLCTool/gurux/include/GXXmlReader.h \
    PLCTool/gurux/include/GXXmlWriter.h \
    PLCTool/gurux/include/GXXmlWriterSettings.h \
    PLCTool/gurux/include/IGXDLMSBase.h \
    PLCTool/gurux/include/OBiscodes.h \
    PLCTool/gurux/include/TranslatorGeneralTags.h \
    PLCTool/gurux/include/TranslatorSimpleTags.h \
    PLCTool/gurux/include/TranslatorStandardTags.h \
    PLCTool/gurux/include/TranslatorTags.h \
    PLCTool/gurux/include/chipperingenums.h \
    PLCTool/gurux/include/enums.h \
    PLCTool/gurux/include/errorcodes.h \
    PLCTool/util/defs.h \
    PLCTool/util/util.h

for(header, INSTALL_HEADERS) {
  path = $${INSTALL_HEADERS_PREFIX}/$${dirname(header)}
  eval(headers_$${path}.files += $$header)
  eval(headers_$${path}.path += $$path)
  eval(INSTALLS *= headers_$${path})
}


# Desktop file target configuration
unix:  desktop.path  = $$PREFIX/share/applications
unix:  desktop.files = PLCTool/PLCTool.desktop
unix:  icons.path    = $$PREFIX/share/icons/hicolor/256x256/apps/
unix:  icons.files   = PLCTool/Icons/PLCTool.png
unix:  INSTALLS     += desktop icons
