//
// --------------------------------------------------------------------------
//  Gurux Ltd
//
//
//
// Filename:        $HeadURL$
//
// Version:         $Revision$,
//                  $Date$
//                  $Author$
//
// Copyright (c) Gurux Ltd
//
//---------------------------------------------------------------------------
//
//  DESCRIPTION
//
// This file is a part of Gurux Device Framework.
//
// Gurux Device Framework is Open Source software, you can redistribute it
// and/or modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation, version 2 of the License.
// Gurux Device Framework is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY, without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
// See the GNU General Public License for more details.
//
// More information of Gurux products: http://www.gurux.org
//
// This code is licensed under the GNU General Public License v2.
// Full text may be retrieved at http://www.gnu.org/licenses/gpl-2.0.txt
//---------------------------------------------------------------------------

#ifndef TRANSLATOR_TAGS_H
#define TRANSLATOR_TAGS_H

typedef enum
{
    DLMS_TRANSLATOR_TAGS_WRAPPER = 0xFF01,
    DLMS_TRANSLATOR_TAGS_HDLC = 0xFF02,
    DLMS_TRANSLATOR_TAGS_PDU_DLMS = 0xFF03,
    DLMS_TRANSLATOR_TAGS_TARGET_ADDRESS = 0xFF04,
    DLMS_TRANSLATOR_TAGS_SOURCE_ADDRESS = 0xFF05,
    DLMS_TRANSLATOR_TAGS_LIST_OF_VARIABLE_ACCESS_SPECIFICATION = 0xFF06,
    DLMS_TRANSLATOR_TAGS_LIST_OF_DATA = 0xFF07,
    DLMS_TRANSLATOR_TAGS_SUCCESS = 0xFF08,
    DLMS_TRANSLATOR_TAGS_DATA_ACCESS_ERROR = 0xFF09,
    DLMS_TRANSLATOR_TAGS_ATTRIBUTE_DESCRIPTOR = 0xFF0A,
    DLMS_TRANSLATOR_TAGS_CLASS_ID = 0xFF0B,
    DLMS_TRANSLATOR_TAGS_INSTANCE_ID = 0xFF0C,
    DLMS_TRANSLATOR_TAGS_ATTRIBUTE_ID = 0xFF0D,
    DLMS_TRANSLATOR_TAGS_METHOD_INVOCATION_PARAMETERS = 0xFF0E,
    DLMS_TRANSLATOR_TAGS_SELECTOR = 0xFF0F,
    DLMS_TRANSLATOR_TAGS_PARAMETER = 0xFF10,
    DLMS_TRANSLATOR_TAGS_LAST_BLOCK = 0xFF11,
    DLMS_TRANSLATOR_TAGS_BLOCK_NUMBER = 0xFF12,
    DLMS_TRANSLATOR_TAGS_RAW_DATA = 0xFF13,
    DLMS_TRANSLATOR_TAGS_METHOD_DESCRIPTOR = 0xFF14,
    DLMS_TRANSLATOR_TAGS_METHOD_ID = 0xFF15,
    DLMS_TRANSLATOR_TAGS_RESULT = 0xFF16,
    DLMS_TRANSLATOR_TAGS_RETURN_PARAMETERS = 0xFF17,
    DLMS_TRANSLATOR_TAGS_ACCESS_SELECTION = 0xFF18,
    DLMS_TRANSLATOR_TAGS_VALUE = 0xFF19,
    DLMS_TRANSLATOR_TAGS_ACCESS_SELECTOR = 0xFF1A,
    DLMS_TRANSLATOR_TAGS_ACCESS_PARAMETERS = 0xFF1B,
    DLMS_TRANSLATOR_TAGS_ATTRIBUTE_DESCRIPTOR_LIST = 0xFF1C,
    DLMS_TRANSLATOR_TAGS_ATTRIBUTE_DESCRIPTOR_WITH_SELECTION = 0xFF1D,
    DLMS_TRANSLATOR_TAGS_READ_DATA_BLOCK_ACCESS = 0xFF1E,
    DLMS_TRANSLATOR_TAGS_WRITE_DATA_BLOCK_ACCESS = 0xFF1F,
    DLMS_TRANSLATOR_TAGS_DATA = 0xFF20,
    DLMS_TRANSLATOR_TAGS_INVOKE_ID = 0xFF21,
    DLMS_TRANSLATOR_TAGS_DATE_TIME = 0xFF22,
    DLMS_TRANSLATOR_TAGS_REASON = 0xFF23,
    DLMS_TRANSLATOR_TAGS_VARIABLE_ACCESS_SPECIFICATION = 0xFF24,
    DLMS_TRANSLATOR_TAGS_PDU_CSE = 0xFF26,
    DLMS_TRANSLATOR_TAGS_CHOICE = 0xFF27,
    DLMS_TRANSLATOR_TAGS_LONG_INVOKE_ID = 0xFF28,
    DLMS_TRANSLATOR_TAGS_NOTIFICATION_BODY = 0xFF29,
    DLMS_TRANSLATOR_TAGS_DATA_VALUE = 0xFF30,
    DLMS_TRANSLATOR_TAGS_ACCESS_REQUEST_BODY = 0xFF31,
    DLMS_TRANSLATOR_TAGS_LIST_OF_ACCESS_REQUEST_SPECIFICATION = 0xFF32,
    DLMS_TRANSLATOR_TAGS_ACCESS_REQUEST_SPECIFICATION = 0xFF33,
    DLMS_TRANSLATOR_TAGS_ACCESS_REQUEST_LIST_OF_DATA = 0xFF34,
    DLMS_TRANSLATOR_TAGS_ACCESS_RESPONSE_BODY = 0xFF35,
    DLMS_TRANSLATOR_TAGS_LIST_OF_ACCESS_RESPONSE_SPECIFICATION = 0xFF36,
    DLMS_TRANSLATOR_TAGS_ACCESS_RESPONSE_SPECIFICATION = 0xFF37,
    DLMS_TRANSLATOR_TAGS_ACCESS_RESPONSE_LIST_OF_DATA = 0xFF38,
    DLMS_TRANSLATOR_TAGS_SINGLE_RESPONSE = 0xFF39,
    DLMS_TRANSLATOR_TAGS_SERVICE = 0xFF40,
    DLMS_TRANSLATOR_TAGS_SERVICE_ERROR = 0xFF41,
    DLMS_TRANSLATOR_TAGS_INITIATE_ERROR = 0xFF42,
    DLMS_TRANSLATOR_TAGS_CIPHERED_SERVICE = 0xFF43,
    DLMS_TRANSLATOR_TAGS_SYSTEM_TITLE = 0xFF44,
    DLMS_TRANSLATOR_TAGS_DATA_BLOCK = 0xFF45,
    DLMS_TRANSLATOR_TAGS_TRANSACTION_ID = 0xFF46,
    DLMS_TRANSLATOR_TAGS_ORIGINATOR_SYSTEM_TITLE = 0xFF47,
    DLMS_TRANSLATOR_TAGS_RECIPIENT_SYSTEM_TITLE = 0xFF48,
    DLMS_TRANSLATOR_TAGS_OTHER_INFORMATION = 0xFF49,
    DLMS_TRANSLATOR_TAGS_KEY_INFO = 0xFF50,
    DLMS_TRANSLATOR_TAGS_AGREED_KEY = 0xFF51,
    DLMS_TRANSLATOR_TAGS_KEY_PARAMETERS = 0xFF52,
    DLMS_TRANSLATOR_TAGS_KEY_CIPHERED_DATA = 0xFF53,
    DLMS_TRANSLATOR_TAGS_CIPHERED_CONTENT = 0xFF54,
    DLMS_TRANSLATOR_TAGS_ATTRIBUTE_VALUE = 0xFF55,
    DLMS_TRANSLATOR_TAGS_CURRENT_TIME = 0xFF56,
    DLMS_TRANSLATOR_TAGS_TIME = 0xFF57,
    DLMS_TRANSLATOR_TAGS_MAX_INFO_RX = 0xFF58,
    DLMS_TRANSLATOR_TAGS_MAX_INFO_TX = 0xFF59,
    DLMS_TRANSLATOR_TAGS_WINDOW_SIZE_RX = 0xFF60,
    DLMS_TRANSLATOR_TAGS_WINDOW_SIZE_TX = 0xFF61,
    DLMS_TRANSLATOR_TAGS_VALUE_LIST = 0xFF62,
    DLMS_TRANSLATOR_TAGS_DATA_ACCESS_RESULT = 0xFF63,
    DLMS_TRANSLATOR_TAGS_FRAME_TYPE = 0xFF64,
    DLMS_TRANSLATOR_TAGS_BLOCK_CONTROL = 0xFF65,
    DLMS_TRANSLATOR_TAGS_BLOCK_NUMBER_ACK = 0xFF66,
    DLMS_TRANSLATOR_TAGS_BLOCK_DATA = 0xFF67,
    DLMS_TRANSLATOR_TAGS_CONTENTS_DESCRIPTION = 0xFF68,
    DLMS_TRANSLATOR_TAGS_ARRAY_CONTENTS = 0xFF69,
    DLMS_TRANSLATOR_TAGS_NETWORK_ID = 0xFF7A,
    DLMS_TRANSLATOR_TAGS_PHYSICAL_DEVICE_ADDRESS = 0xFF7B,
    DLMS_TRANSLATOR_TAGS_PROTOCOL_VERSION = 0xFF7C,
    DLMS_TRANSLATOR_TAGS_CALLED_AP_TITLE = 0xFF7D,
    DLMS_TRANSLATOR_TAGS_CALLED_AP_INVOCATION_ID = 0xFF7E,
    DLMS_TRANSLATOR_TAGS_CALLED_AE_INVOCATION_ID = 0xFF7F,
    DLMS_TRANSLATOR_TAGS_CALLING_AP_INVOCATION_ID = 0xFF80,
    DLMS_TRANSLATOR_TAGS_CALLED_AE_QUALIFIER = 0xFF81,
    TRANSLATOR_GENERAL_TAGS_RESPONSE_ALLOWED = 0xFF82,
} DLMS_TRANSLATOR_TAGS;
#endif //TRANSLATOR_TAGS_H